version: '3.7'

services:
  database:
    image: postgres:12.7
    container_name: blog_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blogdb
    volumes:
      - blog_db_data:/var/lib/postgresql/data

volumes:
  blog_db_data:
